version: "3.8"

services:
  server:
    build: .
    container_name: calik-tv-server
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "1935:1935" # RTMP
      - "8000:8000" # HTTP Stream
    environment:
      - MONGODB_URI=mongodb://mongo:27017/calik-tv
      - PORT=3000
      - RTMP_PORT=1935
      - STREAM_SECRET=calik-tv-2024
      - JWT_SECRET=calik-tv-super-secret-jwt-key-2024
      - SOCKS5_HOST=
      - SOCKS5_PORT=
      - VIRTUAL_HOST=caliktv.infhex.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=caliktv.infhex.com
      - LETSENCRYPT_EMAIL=yemreucmzz@gmail.com
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
